### ISSUE TITLE
Замечания по Лабораторной работе №1 "invert"

### ISSUE THREAD

**Issue by AniSkyWorker** [panic-torra/oop#3]
- [ ] #define замените на const int, const double и т.д.
- [ ] используя только cpp файлы - бессмысленно разделять объявление функций и их реализацию
- [ ] простые типы не нужно передавать по константным ссылкам, памяти они  занимают немного, а передача по ссылке замедлит работу программы, передавайте в зависимости от назначения или по простой ссылке или по значению
- [ ] не очень хорошо получается, когда в функции TryToGetInvertMatrix происходит PrintMatrix, назавание функции TryToGetInvertMatrix не соответствует выполняемым внутри действиям, советую изменить архитектуру. не нужно использовать TryToGetInvertMatrix как замену main
- [ ] не смысла объявлять матрицу Matrix dstMatrix; до того как прошли проверки. объявляйте - после них.
- [ ] TryToGetInvertMatrix если возвращаемых значения 2 используйте тип bool
- [ ] попробуйте использовать вместо CStyle массивов std::vector или std::array
- [ ] вместо типа short внутри циклов нужно использовать тип std::size_t(если индексы используются для доступа к элементам какого-либо контейнера)

**Comment by AniSkyWorker** [comment]
k = 0.65

**Comment by alexey-malov** [comment]
> используя только cpp файлы - бессмысленно разделять объявление функций и их реализацию

Это может улучшить читаемость кода и позволяет разместить main в начале исходника. В будущем на это внимание не заострять

**Comment by alexey-malov** [comment]
> define замените на const int, const double и т.д.

проверено

**Comment by alexey-malov** [comment]
- [x] Не надо передавать определитель в функцию инвертирования матрицы. Она сама может посчитать его.
- [x] Не надо проверять значение определителя перед вызовом функции инвертирвоания. Это нарушение инкапсуляции.  Операция инвертирования должна быть написана так, чтобы либо вернуть флаг успешности, либо вернуть `boost::optional<Matrix>`

**Comment by alexey-malov** [comment]
- [x] вектор векторов лучше заменить array array-ев

**Comment by alexey-malov** [comment]
- [x] лучше размер матрицы не разделять на количество строк и столбцов т.к. матрица должна быть квадратная

**Comment by alexey-malov** [comment]
> не смысла объявлять матрицу Matrix dstMatrix; до того как прошли проверки. объявляйте - после них.

исправлено

**Comment by alexey-malov** [comment]
можно закрыть
