### ISSUE TITLE
Замечания по Vector

### ISSUE THREAD

**Issue by alexey-malov** [panic-torra/oop#4]
- [ ] Исходники в проекте не должны лежать в папке "файлы ресурсов"

**Comment by alexey-malov** [comment]
- [ ] структура тестов должна быть такой, чтобы читаться как описание тестируемой функции или класса, а не условия в которых она тестируется
- [ ] Нет теста,  проверяющего работу функции ProcessVector с пустым массивом
- Функция ProcessVector
  - возвращает пустой вектор из пустого вектора
  - не меняет массив, содержащий единственный ненулевой элемент
  - умножает каждый элемента на максимальный и делит на минимальный
  - не меняет массив, в котором минимальный элемент равен нулю

**Comment by alexey-malov** [comment]
``` c++
    for (size_t i = 0; i < nums.size(); ++i)
    {
        result[i] = nums[i] * *max / *min;
    }
```

используйте алгоритм std::transform, можно использовать boost::phoenix для простоты

**Comment by alexey-malov** [comment]
- [ ] Сортировка не должна выполняться в функции ProcessVector. Она должна выполняться перед выводом результата

**Comment by alexey-malov** [comment]
``` c++
std::vector<double> GetVectorFromFile(std::istream& input)
{
    std::vector<double> nums;
    copy(std::istream_iterator<double>(input), std::istream_iterator<double>(),
        back_inserter(nums));

    return nums;
}
```

достаточно вернуть 

``` c++
return {std::istream_iterator<double>(input), std::istream_iterator<double>()};
```

**Comment by panic-torra** [comment]
Проверено на паре, замечания были устранены

**Comment by alexey-malov** [comment]
принято
